# Generated by Django 6.1 on 2026-08-21 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroslider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default='staticfiles/img/600x600/img1.jpg', upload_to='staticfiles/img/mockups')),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroBottomIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='staticfiles/img/160x160')),
                ('order', models.PositiveIntegerField(default=0)),
                ('heroslider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_icons', to='website.heroslider')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
