# Generated by Django 6.1 on 2026-08-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
