# Generated by Django 6.1 on 2026-08-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefeature',
            name='icon',
            field=models.FileField(default='svg/illustrations/oc-protected-card.svg', upload_to='svg/illustrations/'),
        ),
    ]
