# Generated by Django 6.1 on 2026-08-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_heroslider_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslider',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
