# Generated by Django 6.1 on 2026-08-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_heroslider_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobottomicon',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
