# Generated by Django 6.1 on 2026-08-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_footercolumn_headermenuitem_footerlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerlink',
            name='column',
        ),
        migrations.DeleteModel(
            name='HeaderMenuItem',
        ),
        migrations.DeleteModel(
            name='FooterColumn',
        ),
        migrations.DeleteModel(
            name='FooterLink',
        ),
    ]
