# Generated by Django 6.1 on 2026-08-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_footercolumn_headermenuitem_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('role', models.CharField(max_length=200, verbose_name='سمت (مثلاً: مدیر پروژه)')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی کوتاه')),
                ('image', models.ImageField(upload_to='team/', verbose_name='تصویر پروفایل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت نمایش')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='headermenuitem',
            options={'ordering': ['order']},
        ),
    ]
