# Generated by Django 6.1 on 2026-08-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_teammember_alter_headermenuitem_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
