# Generated by Django 6.1 on 2026-08-26 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_contactmessage_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='فرمت SVG یا PNG با پس\u200cزمینه\u200cی شفاف پیشنهاد می\u200cشود', null=True, upload_to='site/logo/', verbose_name='لوگوی سایت')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon/', verbose_name='فاوآیکون')),
                ('site_name', models.CharField(default='Front', max_length=100, verbose_name='نام سایت')),
                ('primary_color', models.CharField(default='#377DFF', help_text='#377DFF کد هگز مثل', max_length=7, verbose_name='رنگ اصلی تم')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='رنگ پس\u200cزمینه\u200cی اصلی')),
                ('input_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='رنگ فیلد ها(input)')),
                ('font_family', models.CharField(default='sans-serif', help_text="نام دقیق فونت را بنویسید، مثلاً: 'Vazirmatn', sans-serif", max_length=100, verbose_name='نام خانواده فونت (Font Family)')),
                ('custom_font_file', models.FileField(blank=True, help_text='فایل با فرمت .woff2', null=True, upload_to='fonts/')),
                ('custom_font_name', models.CharField(blank=True, help_text='نامی که برای فونت انتخاب می\u200cکنید (مثلاً: MyCustomFont)', max_length=100)),
                ('use_custom_font', models.BooleanField(default=False)),
                ('copyright_start_year', models.PositiveIntegerField(default=2024, help_text='مثلاً 2019 — سال پایان به\u200cصورت خودکار سال جاری در نظر گرفته می\u200cشود', verbose_name='سال شروع کپی\u200cرایت')),
                ('developer_name', models.CharField(blank=True, help_text='مثلاً Dmitry Volkov — اگر خالی باشد این خط کلاً نمایش داده نمی\u200cشود', max_length=100, verbose_name='نام سازنده/توسعه\u200cدهنده')),
                ('developer_url', models.URLField(blank=True, verbose_name='لینک سازنده/توسعه\u200cدهنده')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('address_map', models.URLField(blank=True, help_text='لینک نقشه گوگل یا نشان', null=True, verbose_name='لینک نقشه')),
                ('contact_content', models.TextField(default='ما همیشه خوشحال می\u200cشویم که به شما کمک کنیم و اطلاعات بیشتری درباره خدماتمان ارائه دهیم. می\u200cتوانید از طریق ایمیل یا پر کردن فرم تماس با ما در ارتباط باشید. از اینکه ما را انتخاب کردید متشکریم!', verbose_name='متن صفحه ارتباط با ما')),
                ('privacy_content', models.TextField(default='ما همیشه خوشحال می\u200cشویم که به شما کمک کنیم و اطلاعات بیشتری درباره خدماتمان ارائه دهیم. می\u200cتوانید از طریق ایمیل یا پر کردن فرم تماس با ما در ارتباط باشید. از اینکه ما را انتخاب کردید متشکریم!', verbose_name='متن صفحه حریم خصوصی')),
                ('About_content', models.TextField(default='شرکت ما با سال\u200cها تجربه در زمینه فروش آنلاین، همواره تلاش کرده است بهترین خدمات را به مشتریان خود ارائه دهد.ما با ارائه محصولات باکیفیت و خدمات پس از فروش عالی، اعتماد شما را ارج می\u200cنهیم', verbose_name='متن صفحه حریم خصوصی')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('instagram', 'اینستاگرام'), ('telegram', 'تلگرام'), ('whatsapp', 'واتساپ'), ('twitter', 'توییتر'), ('youtube', 'یوتیوب'), ('linkedin', 'لینکدین'), ('aparat', 'آپارات'), ('facebook', 'فیسبوک'), ('tiktok', 'تیکتاک'), ('snapp', 'اسنپ'), ('google_play', 'گوگل پلی'), ('app_store', 'اپ استور'), ('custom', 'سایر (دلخواه)')], max_length=20, verbose_name='نوع شبکه اجتماعی')),
                ('custom_name', models.CharField(blank=True, help_text="اگر نوع 'سایر' را انتخاب کردید، نام دلخواه وارد کنید", max_length=50, null=True, verbose_name='نام دلخواه')),
                ('url', models.URLField(help_text='لینک کامل صفحه شبکه اجتماعی', verbose_name='آدرس لینک')),
                ('icon', models.ImageField(help_text='تصویر آیکون با فرمت PNG یا SVG (حداقل ۳۲x۳۲ پیکسل)', upload_to='social_media/icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp'])], verbose_name='آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, help_text='عدد کوچکتر، نمایش بالاتر', verbose_name='ترتیب نمایش')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='در تب جدید باز شود')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه\u200cهای اجتماعی',
                'ordering': ['order', 'name'],
                'unique_together': {('name', 'url')},
            },
        ),
    ]
