# Generated by Django 6.1 on 2026-08-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_sitesettings_socialmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='site/favicon/', verbose_name='فاوآیکون'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(blank=True, help_text='فرمت SVG یا PNG با پس\u200cزمینه\u200cی شفاف پیشنهاد می\u200cشود', null=True, upload_to='site/logo/', verbose_name='لوگوی سایت'),
        ),
    ]
