# Generated by Django 6.1 on 2026-08-27 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_socialmedia_options_alter_sitesettings_favicon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['order', 'name'], 'verbose_name': 'شبکه اجتماعی', 'verbose_name_plural': 'شبکه\u200cهای اجتماعی'},
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='custom_icon_html',
            field=models.TextField(blank=True, help_text="اگر سبک 'سایر' را انتخاب کردید، کد HTML آیکون را اینجا وارد کنید", null=True, verbose_name='کد HTML آیکون دلخواه'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='icon_class',
            field=models.CharField(default='bi-link', help_text='مثال: bi-facebook, bi-twitter, bi-instagram, bi-github', max_length=100, verbose_name='کلاس آیکون'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='icon_style',
            field=models.CharField(choices=[('bi', 'Bootstrap Icons'), ('fab', 'Font Awesome (Brands)'), ('fas', 'Font Awesome (Solid)'), ('fa', 'Font Awesome'), ('custom', 'سایر')], default='bi', help_text='نوع کتابخانه آیکون', max_length=20, verbose_name='سبک آیکون'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.ImageField(blank=True, help_text='تصویر آیکون با فرمت PNG یا SVG (حداقل ۳۲x۳۲ پیکسل)', null=True, upload_to='social_media/icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp'])], verbose_name='آیکون'),
        ),
    ]
