# Generated by Django 6.1 on 2026-08-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_socialmedia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='show_in_footer',
            field=models.BooleanField(default=False, verbose_name='نمایش در فوتر'),
        ),
    ]
