# Generated by Django 6.1 on 2026-08-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_socialmedia_show_in_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='teammember',
            name='facebook_url',
            field=models.URLField(default='https://'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='google_url',
            field=models.URLField(default='https://'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='twitter_url',
            field=models.URLField(default='https://'),
        ),
    ]
