# Generated by Django 6.1 on 2026-08-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_socialmedia_options_teammember_facebook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='google_url',
        ),
        migrations.AddField(
            model_name='teammember',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک گیت\u200cهاب'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک لینکدین'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک وب\u200cسایت'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک فیسبوک'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک توییتر'),
        ),
    ]
