# Generated by Django 6.1 on 2026-08-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_teammember_google_url_teammember_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='About_content',
            field=models.TextField(default='شرکت ما با سال\u200cها تجربه در زمینه فروش آنلاین، همواره تلاش کرده است بهترین خدمات را به مشتریان خود ارائه دهد.ما با ارائه محصولات باکیفیت و خدمات پس از فروش عالی، اعتماد شما را ارج می\u200cنهیم', verbose_name='متن صفحه درباره ما'),
        ),
    ]
