# Generated by Django 6.1 on 2026-08-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_sitesettings_about_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='link_hover',
            field=models.CharField(default='#1366ff', max_length=7, verbose_name='رنگ لینک ها درحالت هاور'),
        ),
    ]
