# Generated by Django 6.1 on 2026-08-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_sitesettings_link_hover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='About_content',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_content',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='privacy_content',
        ),
    ]
