# Generated by Django 6.1 on 2026-08-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_remove_sitesettings_about_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_content',
            field=models.TextField(default='شرکت ما با سال\u200cها تجربه در زمینه فروش آنلاین، همواره تلاش کرده است بهترین خدمات را به مشتریان خود ارائه دهد.ما با ارائه محصولات باکیفیت و خدمات پس از فروش عالی، اعتماد شما را ارج می\u200cنهیم', verbose_name='متن صفحه درباره ما'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(max_length=200, null=True, verbose_name='موضوع صفحه درباره ما'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_content',
            field=models.TextField(default='ما همیشه خوشحال می\u200cشویم که به شما کمک کنیم و اطلاعات بیشتری درباره خدماتمان ارائه دهیم. می\u200cتوانید از طریق ایمیل یا پر کردن فرم تماس با ما در ارتباط باشید. از اینکه ما را انتخاب کردید متشکریم!', verbose_name='متن صفحه ارتباط با ما'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_title',
            field=models.CharField(max_length=200, null=True, verbose_name='موضوع صفحه ارتباط با ما'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_content',
            field=models.TextField(default='ما همیشه خوشحال می\u200cشویم که به شما کمک کنیم و اطلاعات بیشتری درباره خدماتمان ارائه دهیم. می\u200cتوانید از طریق ایمیل یا پر کردن فرم تماس با ما در ارتباط باشید. از اینکه ما را انتخاب کردید متشکریم!', verbose_name='متن صفحه حریم خصوصی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_title',
            field=models.CharField(max_length=200, null=True, verbose_name='موضوع صفحه حفاظت و حریم خصوصی'),
        ),
    ]
