# Generated by Django 6.1 on 2026-08-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_sitesettings_about_content_sitesettings_about_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='secondery_color',
            field=models.CharField(default='#677788', help_text='#677788 کد هگز مثل', max_length=7, verbose_name='رنگ نوشته ها'),
        ),
    ]
