# Generated by Django 6.1 on 2026-08-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_sitesettings_secondery_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=200, null=True, verbose_name='موضوع صفحه درباره ما')),
                ('about_content', models.TextField(default='شرکت ما با سال\u200cها تجربه در زمینه فروش آنلاین، همواره تلاش کرده است بهترین خدمات را به مشتریان خود ارائه دهد.ما با ارائه محصولات باکیفیت و خدمات پس از فروش عالی، اعتماد شما را ارج می\u200cنهیم', verbose_name='متن صفحه درباره ما')),
            ],
        ),
        migrations.CreateModel(
            name='ContactSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('address_map', models.URLField(blank=True, help_text='لینک نقشه گوگل یا نشان', null=True, verbose_name='لینک نقشه')),
                ('contact_title', models.CharField(max_length=200, null=True, verbose_name='موضوع صفحه ارتباط با ما')),
                ('contact_content', models.TextField(default='ما همیشه خوشحال می\u200cشویم که به شما کمک کنیم و اطلاعات بیشتری درباره خدماتمان ارائه دهیم. می\u200cتوانید از طریق ایمیل یا پر کردن فرم تماس با ما در ارتباط باشید. از اینکه ما را انتخاب کردید متشکریم!', verbose_name='متن صفحه ارتباط با ما')),
            ],
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
