# Generated by Django 6.1 on 2026-08-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_aboutsetting_contactsetting_delete_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_title', models.CharField(default='سیاست حفظ حریم خصوصی', max_length=200, verbose_name='عنوان صفحه حریم خصوصی')),
                ('privacy_content', models.TextField(default='ما در {{site_name}} به حریم خصوصی کاربران خود احترام می\u200cگذاریم...', verbose_name='متن مقدمه')),
                ('collect_personal', models.BooleanField(default=True, verbose_name='جمع\u200cآوری اطلاعات شخصی (نام، ایمیل)')),
                ('collect_technical', models.BooleanField(default=True, verbose_name='جمع\u200cآوری اطلاعات فنی (IP، مرورگر)')),
                ('collect_cookies', models.BooleanField(default=True, verbose_name='استفاده از کوکی')),
                ('collect_phone', models.BooleanField(default=True, verbose_name='جمع\u200cآوری شماره تماس')),
                ('collect_address', models.BooleanField(default=True, verbose_name='جمع\u200cآوری آدرس تحویل')),
                ('use_improve', models.BooleanField(default=True, verbose_name='بهبود خدمات')),
                ('use_notify', models.BooleanField(default=True, verbose_name='ارسال اطلاع\u200cرسانی')),
                ('use_analytics', models.BooleanField(default=True, verbose_name='تحلیل رفتار کاربران')),
                ('use_security', models.BooleanField(default=True, verbose_name='پیشگیری از تخلف')),
                ('use_shipping', models.BooleanField(default=True, verbose_name='پردازش سفارشات')),
                ('cookie_enabled', models.BooleanField(default=True, verbose_name='کوکی فعال است')),
                ('cookie_description', models.TextField(default='ما از کوکی\u200cها برای ذخیره تنظیمات کاربر استفاده می\u200cکنیم...', verbose_name='توضیحات کوکی')),
                ('third_party_limited', models.BooleanField(default=True, verbose_name='اشتراک محدود با ثالث')),
                ('third_party_description', models.TextField(default='ما اطلاعات شخصی شما را به هیچ شخص ثالثی نمی\u200cفروشیم...', verbose_name='توضیحات اشتراک با ثالث')),
                ('third_party_shipping', models.BooleanField(default=True, verbose_name='اشتراک با شرکت\u200cهای حمل و نقل')),
                ('third_party_payment', models.BooleanField(default=True, verbose_name='اشتراک با درگاه\u200cهای پرداخت')),
                ('third_party_legal', models.BooleanField(default=True, verbose_name='اشتراک با مراجع قانونی')),
                ('security_https', models.BooleanField(default=True, verbose_name='استفاده از HTTPS')),
                ('security_password_hash', models.BooleanField(default=True, verbose_name='رمزنگاری رمز عبور')),
                ('security_access_limit', models.BooleanField(default=True, verbose_name='محدودیت دسترسی')),
                ('security_backup', models.BooleanField(default=True, verbose_name='پشتیبان\u200cگیری منظم')),
                ('rights_access', models.BooleanField(default=True, verbose_name='دسترسی به اطلاعات')),
                ('rights_edit', models.BooleanField(default=True, verbose_name='ویرایش اطلاعات')),
                ('rights_delete', models.BooleanField(default=True, verbose_name='حذف حساب کاربری')),
                ('rights_unsubscribe', models.BooleanField(default=True, verbose_name='لغو اشتراک')),
                ('rights_export', models.BooleanField(default=True, verbose_name='خروجی اطلاعات')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, help_text='فرمت SVG یا PNG با پس\u200cزمینه\u200cی شفاف پیشنهاد می\u200cشود', null=True, upload_to='site/logo/', verbose_name='لوگوی سایت')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='site/favicon/', verbose_name='فاوآیکون')),
                ('site_name', models.CharField(default='Front', max_length=100, verbose_name='نام سایت')),
                ('primary_color', models.CharField(default='#377DFF', help_text='#377DFF کد هگز مثل', max_length=7, verbose_name='رنگ اصلی تم')),
                ('secondery_color', models.CharField(default='#677788', help_text='#677788 کد هگز مثل', max_length=7, verbose_name='رنگ نوشته ها')),
                ('link_hover', models.CharField(default='#1366ff', max_length=7, verbose_name='رنگ لینک ها درحالت هاور')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='رنگ پس\u200cزمینه\u200cی اصلی')),
                ('input_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='رنگ فیلد ها(input)')),
                ('font_family', models.CharField(default='sans-serif', help_text="نام دقیق فونت را بنویسید، مثلاً: 'Vazirmatn', sans-serif", max_length=100, verbose_name='نام خانواده فونت (Font Family)')),
                ('custom_font_file', models.FileField(blank=True, help_text='فایل با فرمت .woff2', null=True, upload_to='fonts/')),
                ('custom_font_name', models.CharField(blank=True, help_text='نامی که برای فونت انتخاب می\u200cکنید (مثلاً: MyCustomFont)', max_length=100)),
                ('use_custom_font', models.BooleanField(default=False)),
                ('copyright_start_year', models.PositiveIntegerField(default=2024, help_text='مثلاً 2019 — سال پایان به\u200cصورت خودکار سال جاری در نظر گرفته می\u200cشود', verbose_name='سال شروع کپی\u200cرایت')),
                ('developer_name', models.CharField(blank=True, help_text='مثلاً Dmitry Volkov — اگر خالی باشد این خط کلاً نمایش داده نمی\u200cشود', max_length=100, verbose_name='نام سازنده/توسعه\u200cدهنده')),
                ('developer_url', models.URLField(blank=True, verbose_name='لینک سازنده/توسعه\u200cدهنده')),
            ],
        ),
    ]
