# Generated by Django 6.1 on 2026-08-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_privacysettings_sitesettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteSettings',
            new_name='SiteSetting',
        ),
    ]
