# Generated by Django 6.1 on 2026-08-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_rename_sitesettings_sitesetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivacySettings',
            new_name='PrivacySetting',
        ),
    ]
