# Generated by Django 6.1 on 2026-08-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_rename_privacysettings_privacysetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('introduction', 'مقدمه'), ('collect_info', 'اطلاعات جمع\u200cآوری شده'), ('how_use', 'نحوه استفاده'), ('cookies', 'کوکی\u200cها'), ('third_party', 'اشتراک با ثالث'), ('security', 'امنیت'), ('user_rights', 'حقوق کاربران'), ('custom', 'سکشن دلخواه')], default='custom', max_length=50, verbose_name='نوع سکشن')),
                ('title', models.CharField(help_text='عنوانی که در صفحه نمایش داده می\u200cشود', max_length=200, verbose_name='عنوان سکشن')),
                ('icon', models.CharField(blank=True, help_text='مثلاً: fa-shield-alt, fa-info-circle, fa-database', max_length=50, verbose_name='آیکون')),
                ('description', models.TextField(blank=True, help_text='توضیح کوتاه بالای لیست آیتم\u200cها (اختیاری)', verbose_name='توضیحات مقدماتی سکشن')),
                ('items', models.JSONField(default=list, help_text='[\n            {"title": "عنوان آیتم", \n             "description": "توضیحات آیتم", \n             "icon": "fa-user",\n             "badge": "فعال",\n             "badge_style": "active"}\n        ]', verbose_name='آیتم\u200cهای سکشن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='collect_address',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='collect_cookies',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='collect_personal',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='collect_phone',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='collect_technical',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='privacy_content',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='privacy_title',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='rights_access',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='rights_delete',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='rights_edit',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='rights_export',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='rights_unsubscribe',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='security_access_limit',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='security_backup',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='security_https',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='security_password_hash',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='third_party_description',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='third_party_legal',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='third_party_limited',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='third_party_payment',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='third_party_shipping',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='use_analytics',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='use_improve',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='use_notify',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='use_security',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='use_shipping',
        ),
        migrations.AddField(
            model_name='privacysetting',
            name='introduction_text',
            field=models.TextField(default='ما به حریم خصوصی کاربران خود احترام می\u200cگذاریم. این سند نحوه جمع\u200cآوری، استفاده و محافظت از اطلاعات شما را شرح می\u200cدهد. استفاده از سایت ما به معنای پذیرش این سیاست است.', verbose_name='متن مقدمه'),
        ),
        migrations.AddField(
            model_name='privacysetting',
            name='last_update',
            field=models.DateField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی'),
        ),
        migrations.AddField(
            model_name='privacysetting',
            name='page_subtitle',
            field=models.CharField(blank=True, help_text='متن زیر عنوان اصلی', max_length=200, verbose_name='زیرعنوان صفحه'),
        ),
        migrations.AddField(
            model_name='privacysetting',
            name='page_title',
            field=models.CharField(default='سیاست حفظ حریم خصوصی', max_length=200, verbose_name='عنوان صفحه'),
        ),
        migrations.AlterField(
            model_name='privacysetting',
            name='cookie_description',
            field=models.TextField(default='ما از کوکی\u200cها برای ذخیره تنظیمات کاربر، احراز هویت و تحلیل بازدید استفاده می\u200cکنیم. شما می\u200cتوانید در مرورگر خود کوکی\u200cها را غیرفعال کنید، اما ممکن است برخی امکانات سایت با اختلال مواجه شوند.', verbose_name='توضیحات کوکی'),
        ),
    ]
