# Generated by Django 6.1 on 2026-08-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_privacysection_remove_privacysetting_collect_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacysection',
            name='items',
        ),
    ]
