# Generated by Django 6.1 on 2026-08-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_remove_privacysection_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacysetting',
            name='cookie_description',
        ),
        migrations.RemoveField(
            model_name='privacysetting',
            name='cookie_enabled',
        ),
    ]
