# Generated by Django 6.1 on 2026-08-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_remove_privacysetting_cookie_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreloaderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='فعال بودن Preloader')),
                ('spinner_type', models.CharField(choices=[('spinner', 'اسپینر دایره\u200cای'), ('pulse', 'اسپینر نقطه\u200cای'), ('dots', 'سه نقطه'), ('logo', 'لوگوی سایت'), ('progress', 'نوار پیشرفت'), ('text', 'متن متحرک')], default='spinner', help_text='انتخاب کنید که کدام اسپینر نمایش داده شود', max_length=20, verbose_name='نوع اسپینر')),
                ('background_color', models.CharField(default='#FFFFFF', help_text='کد هگز رنگ پس\u200cزمینه', max_length=7, verbose_name='رنگ پس\u200cزمینه')),
                ('primary_color', models.CharField(default='#377DFF', help_text='رنگ اسپینر یا نوار پیشرفت', max_length=7, verbose_name='رنگ اصلی اسپینر')),
                ('text_color', models.CharField(default='#677788', help_text='رنگ متن زیر اسپینر', max_length=7, verbose_name='رنگ متن')),
                ('loading_text', models.CharField(default='در حال بارگذاری...', help_text='متنی که زیر اسپینر نمایش داده می\u200cشود', max_length=100, verbose_name='متن نمایشی')),
                ('logo', models.ImageField(blank=True, help_text="اگر نوع اسپینر 'لوگوی سایت' را انتخاب کنید، این لوگو نمایش داده می\u200cشود", null=True, upload_to='preloader/', verbose_name='لوگوی Preloader')),
                ('display_duration', models.PositiveIntegerField(default=1500, help_text='مثلاً 1500 = 1.5 ثانیه', verbose_name='زمان نمایش (میلی\u200cثانیه)')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات Preloader',
            },
        ),
        migrations.AlterField(
            model_name='privacysetting',
            name='page_subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='زیرعنوان صفحه'),
        ),
    ]
