# Generated by Django 6.1 on 2026-08-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_preloadersetting_alter_privacysetting_page_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preloadersetting',
            options={},
        ),
        migrations.AlterField(
            model_name='preloadersetting',
            name='loading_text',
            field=models.CharField(default='در حال بارگذاری...', help_text='متنی که زیر اسپینر نمایش داده می\u200cشود', max_length=100, null=True, verbose_name='متن نمایشی'),
        ),
    ]
