# Generated by Django 6.1 on 2026-08-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_alter_preloadersetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preloadersetting',
            name='loading_text',
            field=models.CharField(blank=True, default='در حال بارگذاری...', help_text='متنی که زیر اسپینر نمایش داده می\u200cشود', max_length=100, verbose_name='متن نمایشی'),
        ),
    ]
