# Generated by Django 6.1 on 2026-08-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_preloadersetting_loading_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن لودر')),
                ('logo', models.FileField(blank=True, help_text='تصویر لوگو (PNG یا SVG ترجیح داده می\u200cشود)', null=True, upload_to='site/logo/', verbose_name='لوگوی لودر')),
                ('loading_text', models.CharField(default='در حال بارگذاری', max_length=100, verbose_name='متن بارگذاری')),
                ('loading_text_color', models.CharField(default='#333333', help_text='مثلاً: #333333 یا rgb(51, 51, 51)', max_length=20, verbose_name='رنگ متن بارگذاری')),
                ('background_color', models.CharField(default='#ffffff', help_text='مثلاً: #ffffff یا white', max_length=20, verbose_name='رنگ پس\u200cزمینه لودر')),
                ('logo_width', models.PositiveIntegerField(default=120, help_text='عرض لوگو بر حسب پیکسل', verbose_name='عرض لوگو (پیکسل)')),
                ('logo_animation', models.CharField(choices=[('spin', 'چرخش دور خود'), ('pulse', 'نبض\u200cدار (بزرگ و کوچک)'), ('bounce', 'پرشی'), ('none', 'بدون انیمیشن')], default='spin', max_length=20, verbose_name='نوع انیمیشن لوگو')),
                ('logo_animation_duration', models.FloatField(default=1.5, help_text='مثلاً 1.5 یعنی هر 1.5 ثانیه یک دور کامل', verbose_name='مدت زمان هر دور انیمیشن (ثانیه)')),
                ('show_spinner', models.BooleanField(default=False, verbose_name='نمایش دایره\u200cی چرخان (اسپینر)')),
                ('spinner_color', models.CharField(default='#3498db', help_text='مثلاً: #3498db', max_length=20, verbose_name='رنگ دایره\u200cی چرخان')),
                ('spinner_size', models.PositiveIntegerField(default=80, verbose_name='اندازه دایره\u200cی چرخان (پیکسل)')),
                ('show_progress_bar', models.BooleanField(default=False, verbose_name='نمایش نوار پیشرفت')),
                ('progress_bar_color', models.CharField(default='#3498db', max_length=20, verbose_name='رنگ نوار پیشرفت')),
                ('minimum_display_time', models.PositiveIntegerField(default=0, help_text='مثلاً 1500 یعنی حداقل 1.5 ثانیه نمایش داده شود (0 یعنی بدون محدودیت)', verbose_name='حداقل زمان نمایش (میلی\u200cثانیه)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PreloaderSetting',
        ),
    ]
