# Generated by Django 6.1 on 2026-09-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_loadersetting_delete_preloadersetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='updated_date',
            field=models.DateTimeField(),
        ),
    ]
