# Generated by Django 6.1 on 2026-09-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_alter_footerlink_published_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerlink',
            name='column',
        ),
        migrations.DeleteModel(
            name='FooterColumn',
        ),
        migrations.DeleteModel(
            name='FooterLink',
        ),
    ]
