# Generated by Django 6.1 on 2026-09-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_footercolumn_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='قوانین و مقررات', max_length=200)),
                ('page_subtitle', models.CharField(blank=True, max_length=200)),
                ('introduction_text', models.TextField(default='با استفاده از خدمات ما، شما با قوانین زیر موافقت می\u200cکنید...')),
                ('last_update', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات قوانین',
                'verbose_name_plural': 'تنظیمات قوانین',
            },
        ),
    ]
