# Generated by Django 6.1 on 2026-09-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_termsconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('acceptance', 'پذیرش قوانین'), ('account', 'حساب کاربری'), ('orders', 'سفارش و پرداخت'), ('shipping', 'ارسال و تحویل'), ('returns', 'مرجوعی و بازگشت'), ('warranty', 'گارانتی'), ('prohibited', 'رفتارهای ممنوعه'), ('intellectual', 'مالکیت معنوی'), ('liability', 'محدودیت مسئولیت'), ('changes', 'تغییر قوانین'), ('contact', 'تماس با ما'), ('custom', 'سکشن دلخواه')], default='custom', max_length=50, verbose_name='نوع سکشن')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سکشن')),
                ('icon', models.CharField(blank=True, help_text='مثلاً: fa-file-contract, fa-user-shield', max_length=50, verbose_name='آیکون')),
                ('content', models.TextField(help_text='می\u200cتوانید HTML یا Markdown بنویسید', verbose_name='محتوا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سکشن قوانین',
                'verbose_name_plural': 'سکشن\u200cهای قوانین',
                'ordering': ['order'],
            },
        ),
    ]
