# Generated by Django 6.1 on 2026-09-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_termssection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsconfig',
            options={},
        ),
        migrations.AlterModelOptions(
            name='termssection',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='contactsetting',
            name='icon',
            field=models.CharField(blank=True, help_text='مثلاً: bi-pen', max_length=50, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='privacysection',
            name='icon',
            field=models.CharField(blank=True, help_text='مثلاً: bi-pen', max_length=50, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='privacysetting',
            name='introduction_text',
            field=models.TextField(default='ما به حریم خصوصی کاربران خود احترام می\u200cگذاریم. این سند نحوه جمع\u200cآوری، استفاده و محافظت از اطلاعات شما را شرح می\u200cدهد. استفاده از سایت ما به معنای پذیرش این سیاست است.', help_text='می\u200cتوانید HTML یا Markdown بنویسید', verbose_name='متن مقدمه'),
        ),
        migrations.AlterField(
            model_name='termssection',
            name='icon',
            field=models.CharField(blank=True, help_text='مثلاً: bi-pen', max_length=50, verbose_name='آیکون'),
        ),
    ]
