# Generated by Django 6.1 on 2026-09-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_alter_termsconfig_options_alter_termssection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsetting',
            name='about_subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان'),
        ),
        migrations.AddField(
            model_name='aboutsetting',
            name='gallery',
            field=models.JSONField(blank=True, default=list, help_text='لیستی از آدرس تصاویر: ["/media/about/1.jpg", ...]', verbose_name='گالری تصاویر'),
        ),
        migrations.AddField(
            model_name='aboutsetting',
            name='icon',
            field=models.CharField(blank=True, default='info-circle', max_length=50, verbose_name='آیکون'),
        ),
        migrations.AddField(
            model_name='aboutsetting',
            name='info_content',
            field=models.TextField(blank=True, default='از سال ۱۳۸۵، ما به کسب\u200cوکارهای مختلف کمک کرده\u200cایم...', verbose_name='محتوای بخش اطلاعات'),
        ),
        migrations.AddField(
            model_name='aboutsetting',
            name='info_title',
            field=models.CharField(blank=True, default='ابزارها باید با کاربر سازگار شوند، نه برعکس.', max_length=300, verbose_name='عنوان بخش اطلاعات'),
        ),
        migrations.AddField(
            model_name='aboutsetting',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا'),
        ),
        migrations.AddField(
            model_name='aboutsetting',
            name='stat_1_label',
            field=models.CharField(blank=True, default='سال در تجارت', max_length=100, verbose_name='آمار ۱ — برچسب'),
        ),
        migrations.AddField(
            model_name='aboutsetting',
            name='stat_1_number',
            field=models.CharField(blank=True, default='7', help_text='مثلاً: 7 یا 3.5k+ یا 85%', max_length=50, verbose_name='آمار ۱ — عدد'),
        ),
        migrations.AddField(
            model_name='aboutsetting',
            name='stat_2_label',
            field=models.CharField(blank=True, default='نسخه فروخته شده', max_length=100, verbose_name='آمار ۲ — برچسب'),
        ),
        migrations.AddField(
            model_name='aboutsetting',
            name='stat_2_number',
            field=models.CharField(blank=True, default='3.5k+', max_length=50, verbose_name='آمار ۲ — عدد'),
        ),
        migrations.AddField(
            model_name='aboutsetting',
            name='stat_3_label',
            field=models.CharField(blank=True, default='مشتریان خوشحال', max_length=100, verbose_name='آمار ۳ — برچسب'),
        ),
        migrations.AddField(
            model_name='aboutsetting',
            name='stat_3_number',
            field=models.CharField(blank=True, default='85%', max_length=50, verbose_name='آمار ۳ — عدد'),
        ),
        migrations.AddField(
            model_name='aboutsetting',
            name='stat_4_label',
            field=models.CharField(blank=True, default='پشتیبانی', max_length=100, verbose_name='آمار ۴ — برچسب'),
        ),
        migrations.AddField(
            model_name='aboutsetting',
            name='stat_4_number',
            field=models.CharField(blank=True, default='24/7', max_length=50, verbose_name='آمار ۴ — عدد'),
        ),
        migrations.AlterField(
            model_name='aboutsetting',
            name='about_content',
            field=models.TextField(blank=True, default='شرکت ما با سال\u200cها تجربه در زمینه فروش آنلاین...', verbose_name='متن معرفی'),
        ),
        migrations.AlterField(
            model_name='aboutsetting',
            name='about_title',
            field=models.CharField(blank=True, default='درباره ما', max_length=200, verbose_name='عنوان صفحه'),
        ),
    ]
