# Generated by Django 6.1 on 2026-09-23 16:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_activationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationtoken',
            name='otp_code',
            field=models.CharField(default=accounts.models.generate_otp, max_length=6, verbose_name='کد فعال\u200cسازی'),
        ),
    ]
