# Generated by Django 6.1 on 2026-08-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_date']},
        ),
    ]
