# Generated by Django 6.1 on 2026-08-24 22:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_reviewreaction_review_dislikes_review_likes_and_more'),
        ('shop', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewreaction',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='reviewreaction',
            name='review_revi_user_id_51be13_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_revi_product_df468e_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_revi_user_id_956523_idx',
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.RemoveField(
            model_name='review',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='review',
            name='published_date',
        ),
        migrations.DeleteModel(
            name='ReviewReaction',
        ),
    ]
