# Generated by Django 6.1 on 2026-08-24 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_reviewreaction_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
