# Generated by Django 6.1 on 2026-08-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_review_dislikes_review_likes_review_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
